### ISSUE TITLE
Driver won't init

### ISSUE THREAD

**Issue by kem0x** [kkent030315/libmhyprot#1]
compiling on Debug/x64 C++17 Multi-Byte, Tried all configs but somehow the driver won't init "no errors at all"
![image](https://user-images.githubusercontent.com/19430119/96373250-8ece7500-116b-11eb-995d-07ff37c6f9a1.png)

**Comment by Th3C0D3R** [comment]
Run as admin?

**Comment by kem0x** [comment]
sure
![image](https://user-images.githubusercontent.com/19430119/96374485-5fbc0180-1173-11eb-9072-79e702a86063.png)

**Comment by kkent030315** [comment]
Hello sir.
Please check error details by `GetLastError()` and it might be because of there is another `mhyprot` service running or registered.

**Comment by kem0x** [comment]
might be the game “genshin impact” ?
, if so you might add checks if the driver is alr loaded so you can utilize the current one?

**Comment by kkent030315** [comment]
> might be the game “genshin impact” ?
> , if so you might add checks if the driver is alr loaded so you can utilize the current one?

I've already checks that in [service_utils.cpp#L34](https://github.com/kkent030315/libmhyprot/blob/main/src/service_utils.cpp#L34) but it still should happens if another name of service running on the system.

I can't remember the default service name.
Could you tell me what is the default service name registered by Genshin launcher?

**Comment by kem0x** [comment]
i checked and the service wasn’t even created and it couldn’t init too, the game one is “mhyprot2”.

**Comment by kkent030315** [comment]
How about `printf("0x%lX\n", GetLastError());` ?
You can post it here and I can help you with it more clear.

**Comment by kem0x** [comment]
excuse me for being late, 
![image](https://user-images.githubusercontent.com/19430119/96511362-44c6bb80-125f-11eb-991a-87bc740568e0.png)
i think its something caused by the game ? (sorry i don't work with signed drivers most of the time so i don't know)
![image](https://user-images.githubusercontent.com/19430119/96511595-953e1900-125f-11eb-9f13-36ad467b4158.png)

**Comment by Th3C0D3R** [comment]
As the description said. The driver is marked for delete.
A driver is only marked if it is running. If it is stopped it will be deleted directly. 
So the thing is: this program creates the driver new from memory
When de exploit uninit/unload it, the driver will be deleted. Maybe there was something bad and the driver could not get deleted directly instead just marked for deletion after the next reboot

**Comment by kkent030315** [comment]
Thanks for providing information.
It is because the service marked for delete, it means that the mhyprot driver is running and it will be deleted when the service stopped.
You can use commands below to stop the service:

```
sc stop mhyprot
```

Or you can use [ProcessHacker](https://processhacker.sourceforge.io/downloads.php) to operate service(s) more easily.
![3980326](https://user-images.githubusercontent.com/37926134/96515634-a0fdff80-12a0-11eb-8e83-09788e3a8823.png)
Use the search bar on right-top the window.

Additionaly in this case, the service must be stopped before use this library. I'll add exception for like this case or similar situation.

**Comment by kkent030315** [comment]
Just pushed improvements right now on 17d6b0a
Please note that it still has a possibility to get failure due to another name of service is running on the system already. if so, please take action manually like I said on above.

**Comment by kem0x** [comment]
i wanted to make a genshin impact cheat using its anticheat but i guess this is not possible 
this is Acess Denied so probably this happens because the game is on
![image](https://user-images.githubusercontent.com/19430119/96523377-d3dece00-1275-11eb-9bc5-f74382ebbc6e.png)

**Comment by kkent030315** [comment]
I am sorry, I do not support like that illegal behavior.
I also do not have any responsibility for that.

The only one thing I can say is that `0x5` is access denied which means that you do not have much privilege to operate the service.
That's why I declared "administrator required only if the service is not running" on the [CLI](https://github.com/kkent030315/evil-mhyprot-cli)

Follow what Mr. @Th3C0D3R said.
